from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class ToolCallRecord:
    """
    Represents one tool call generated by the LLM.
    """

    step: int
    tool: str
    arguments: Dict[str, Any]


@dataclass
class ToolResultRecord:
    """
    Represents the result returned by one tool execution.
    """

    step: int
    tool: str
    result: Dict[str, Any]


@dataclass
class AgentState:
    """
    State of one CareerPlus agent execution.

    This object contains the explicit state of the agent
    instead of keeping everything implicit inside messages.
    """

    user_query: str

    history: List[Dict[str, Any]] = field(
        default_factory=list
    )

    messages: List[Dict[str, Any]] = field(
        default_factory=list
    )

    current_step: int = 0

    tool_calls: List[ToolCallRecord] = field(
        default_factory=list
    )

    tool_results: List[ToolResultRecord] = field(
        default_factory=list
    )

    final_response: Optional[str] = None

    status: str = "running"

    error: Optional[str] = None

    def add_tool_call(
        self,
        step: int,
        tool: str,
        arguments: Dict[str, Any],
    ) -> None:
        """
        Record a tool call generated by the LLM.
        """

        self.tool_calls.append(
            ToolCallRecord(
                step=step,
                tool=tool,
                arguments=arguments,
            )
        )

    def add_tool_result(
        self,
        step: int,
        tool: str,
        result: Dict[str, Any],
    ) -> None:
        """
        Record a tool execution result.
        """

        self.tool_results.append(
            ToolResultRecord(
                step=step,
                tool=tool,
                result=result,
            )
        )

    def finish(
        self,
        response: str,
    ) -> None:
        """
        Mark the agent execution as successfully completed.
        """

        self.final_response = response
        self.status = "completed"

    def fail(
        self,
        error: str,
    ) -> None:
        """
        Mark the agent execution as failed.
        """

        self.error = error
        self.status = "failed"

    def to_dict(self) -> Dict[str, Any]:
        """
        Convert the state into a JSON-serializable dictionary.
        """

        return {
            "user_query": self.user_query,
            "history": self.history,
            "current_step": self.current_step,
            "tool_calls": [
                {
                    "step": call.step,
                    "tool": call.tool,
                    "arguments": call.arguments,
                }
                for call in self.tool_calls
            ],
            "tool_results": [
                {
                    "step": result.step,
                    "tool": result.tool,
                    "result": result.result,
                }
                for result in self.tool_results
            ],
            "final_response": self.final_response,
            "status": self.status,
            "error": self.error,
        }