from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class ToolCallRecord:
    """
    Represents one tool call generated by the LLM.
    """

    step: int
    tool: str
    arguments: Dict[str, Any]


@dataclass
class ToolResultRecord:
    """
    Represents the result returned by one tool execution.
    """

    step: int
    tool: str
    result: Dict[str, Any]


@dataclass
class AgentState:
    """
    State of one CareerPlus agent execution.

    The uploaded CV is stored separately from the conversation
    messages. It can then be provided only to tools that need it.
    """

    user_query: str

    history: List[Dict[str, Any]] = field(
        default_factory=list
    )

    messages: List[Dict[str, Any]] = field(
        default_factory=list
    )

    # ----------------------------------------------------------
    # CV
    # ----------------------------------------------------------

    cv_text: Optional[str] = None

    # ----------------------------------------------------------
    # Agent execution state
    # ----------------------------------------------------------

    current_step: int = 0

    tool_calls: List[ToolCallRecord] = field(
        default_factory=list
    )

    tool_results: List[ToolResultRecord] = field(
        default_factory=list
    )

    final_response: Optional[str] = None

    status: str = "running"

    error: Optional[str] = None

    # ==========================================================
    # TOOL CALL
    # ==========================================================

    def add_tool_call(
        self,
        step: int,
        tool: str,
        arguments: Dict[str, Any],
    ) -> None:

        self.tool_calls.append(
            ToolCallRecord(
                step=step,
                tool=tool,
                arguments=arguments,
            )
        )

    # ==========================================================
    # TOOL RESULT
    # ==========================================================

    def add_tool_result(
        self,
        step: int,
        tool: str,
        result: Dict[str, Any],
    ) -> None:

        self.tool_results.append(
            ToolResultRecord(
                step=step,
                tool=tool,
                result=result,
            )
        )

    # ==========================================================
    # FINISH
    # ==========================================================

    def finish(
        self,
        response: str,
    ) -> None:

        self.final_response = response
        self.status = "completed"

    # ==========================================================
    # FAIL
    # ==========================================================

    def fail(
        self,
        error: str,
    ) -> None:

        self.error = error
        self.status = "failed"

    # ==========================================================
    # TO DICT
    # ==========================================================

    def to_dict(self) -> Dict[str, Any]:

        return {
            "user_query": self.user_query,

            "history": self.history,

            "current_step": self.current_step,

            "cv_available": self.cv_text is not None,

            "tool_calls": [
                {
                    "step": call.step,
                    "tool": call.tool,
                    "arguments": call.arguments,
                }
                for call in self.tool_calls
            ],

            "tool_results": [
                {
                    "step": result.step,
                    "tool": result.tool,
                    "result": result.result,
                }
                for result in self.tool_results
            ],

            "final_response": self.final_response,

            "status": self.status,

            "error": self.error,
        }