from typing import Any, Dict, List, Literal

from pydantic import BaseModel, Field, ConfigDict



class ChatMessage(BaseModel):
    """
    Message sent as part of the conversation history.

    Only user/assistant messages are accepted from the API client.
    Tool messages are generated internally by the agent.
    """

    role: Literal["user", "assistant"]
    content: str = Field(min_length=1)


class ChatRequest(BaseModel):
    """
    Request body for the /chat endpoint.
    """

    model_config = ConfigDict(extra="forbid")

    message: str = Field(
        ...,
        min_length=1,
        max_length=10_000,
        description="User's message.",
    )

    history: List[ChatMessage] = Field(
        default_factory=list,
        description="Optional previous user/assistant messages.",
    )

    include_trace: bool = Field(
        default=True,
        description=(
            "Return actual generated tool calls in the response. "
            "This does not expose model private reasoning."
        ),
    )


class ToolCallTrace(BaseModel):
    """
    One actual tool call generated by the LLM.
    """

    step: int
    tool: str
    arguments: Dict[str, Any]


class ChatResponse(BaseModel):
    """
    Response returned by the CareerPlus API.
    """

    response: str
    tool_calls: List[ToolCallTrace] = Field(
        default_factory=list
    )

    steps: int
    success: bool = True


class HealthResponse(BaseModel):
    status: str
    service: str
    model: str

class JobSearchRequest(BaseModel):
    query: str = Field(
        ...,
        min_length=1,
        max_length=1000,
        description="Semantic query used to search indexed job offers."
    )

    top_k: int = Field(
        default=5,
        ge=1,
        le=20,
        description="Maximum number of jobs to retrieve."
    )

class JobSearchResponse(BaseModel):
    matches_found: int
    results: List[Dict[str, Any]]


class SendEmailRequest(BaseModel):

    recipient: str = Field(
        ...,
        min_length=3,
        description="Recipient email address.",
    )

    subject: str = Field(
        ...,
        min_length=1,
        max_length=200,
        description="Email subject.",
    )

    body: str = Field(
        ...,
        min_length=1,
        max_length=20_000,
        description="Email body.",
    )


class SendEmailResponse(BaseModel):

    status: str
    message: str
    message_id: str | None = None
    recipient: str